AppWeb24CV/Models/EmailViewModel.cs
namespace AppWeb24CV.Models
{
    public class EmailViewModel
    {
        public string Email { get; set; }
        public string Comentario{ get; set; }
    }
}

AppWeb24CV/Models/ErrorViewModel.cs
namespace AppWeb24CV.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppWeb24CV/Models/Persona.cs
namespace AppWeb24CV.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public DateTime FechaNacimiento { get; set; }

    }
}

AppWeb24CV/Controllers/EjemploController.cs
using AppWeb24CV.Models;
using Microsoft.AspNetCore.Mvc;

namespace AppWeb24CV.Controllers
{
    public class EjemploController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Contacto()
        {
            Persona persona = new Persona();
            persona.Nombre = "Moises";
            persona.Apellidos = "Torres";
            persona.FechaNacimiento = new DateTime(1982, 01, 15);
            return View(persona);
        }
    }
}

AppWeb24CV/Controllers/FormulariosController.cs
using AppWeb24CV.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Net;
using System.Net.Mail;

namespace AppWeb24CV.Controllers
{
    public class FormulariosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult EnviarCorreo(string email, string comentario)
           
        {
            TempData["Email"] = email;
            TempData["Comentario"] = comentario;



            return View("Index");

           
        }

        [HttpPost]
        public IActionResult EnviarInformacion(EmailViewModel model)
        {
            TempData["Email"] = model.Email;
            TempData["Comentario"] = model.Comentario;
            SendEmail(model.Email, model.Comentario);
            
            return View("Index", model);
        }


        public bool SendEmail(string email, string comentario)
        {
            MailMessage mail = new MailMessage();
            SmtpClient smtp = new SmtpClient("mail.shapp.mx", 587);
            smtp.EnableSsl = true;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential("moises.puc@shapp.mx", "Dhaserck_999");
            mail.From = new MailAddress("moises.puc@shapp.mx", "Administrador");
            mail.To.Add(email);
            mail.Subject = "Notificación de contacto";
            mail.IsBodyHtml = true;
            mail.Body = $"Se ha recibido información del correo <h1>{email} </h1> <br/> <p>{email}<p/>";
            smtp.Send(mail);
            return true;
        }


    }
}

AppWeb24CV/Controllers/HomeController.cs
using AppWeb24CV.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppWeb24CV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppWeb24CV/Views/Ejemplo/Contacto.cshtml
@using AppWeb24CV.Models

<h1 class="text-center">Bienvenido @Model.Nombre @Model.Apellidos</h1>
<p class="text-center">
   Tu fecha de nacimiento @Model.FechaNacimiento.ToLongDateString()
    </p>

AppWeb24CV/Views/Ejemplo/Index.cshtml
<h1>Esta es la vista index del controlador ejemplo</h1> 

AppWeb24CV/Views/Formularios/Index.cshtml
@model AppWeb24CV.Models.EmailViewModel
<div class="row">

    @if (TempData["Email"] != null)
    {
        <div class="alert alert-success">
            Se ha recibido la información del correo @TempData["Email"] <br>
            <p class="text-sm-center" @TempData["Comentario"]></p>
        </div>
    }

    <div class="col-12">
        <h2 class="text-center">Ejemplo de envio de información</h2>
        <p class="text-center">Envio de formulario pasando datos de la vista al controlador</p>
    </div>
    <div class="col-8">
        <form asp-action="EnviarInformacion" asp-controller="Formularios" method="post">
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" asp-for="Email" class="form-control" />
            </div>
            <div class="mb-3">
                <label class="form-label">Comentario</label>
                <textarea class="form-control" asp-for="Comentario" rows="4"></textarea>
            </div>
            <button class="btn btn-primary" type="submit">Enviar</button>
        </form>
    </div>
    <div class="col-4">
        <h3 class="text-center">Enviar información al correo capturado</h3>
        <p>Se enviara un correo con la información capturada</p>
    </div>
</div>

AppWeb24CV/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppWeb24CV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppWeb24CV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppWeb24CV.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppWeb24CV</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ejemplo" asp-action="Index">Ejemplos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ejemplo" asp-action="Contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formularios" asp-action="Index">Formulario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AppWeb24CV - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>